name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install tools
      run: |
        sudo apt update
        sudo apt install -y python3-pip
        pip3 install buildozer

    - name: Build APK
      run: |
        buildozer android debug
